### ISSUE TITLE
UI Model/Inventory

### ISSUE THREAD

**Issue by jakubfiala** [wellcometrust/together-science-can#2]
tasks:

- [ ] define different types of section layouts
- [ ] define individual UI components
- [ ] review with Nick
- [ ] create folder/file structure accordingly

This will enable us to create issues for individual components

**Comment by jakubfiala** [comment]
closing this, as it's been done organically over the course of build
